# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_patatachar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body2',
            field=models.TextField(default='pat', verbose_name='Bod2'),
            preserve_default=False,
        ),
    ]
