# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body2',
            field=models.CharField(default='patata', max_length=100, verbose_name='Titleforever'),
        ),
    ]
