# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body2',
        ),
    ]
