# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181010_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='blog/static/blog/img/users/no_image.png', upload_to='blog/static/blog/img/users/', verbose_name='Image'),
        ),
    ]
