# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181011_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/img/users/', verbose_name='Image'),
        ),
    ]
