# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20181011_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='blog/profile/no_image.png', upload_to='blog/profile', verbose_name='Image'),
        ),
    ]
